### ISSUE TITLE
com.intellij.diagnostic.PluginException for deprecated ActionUpdateThread.OLD_EDT

### ISSUE THREAD

**Issue by karvanit** [intellij-elm/intellij-elm#814]
### What happened?

The plugin is written with an older plugin SDK and the newer Idea is throwing an exception because it wants the newer API used in Actions.

### Relevant log output or stack trace

```shell
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.elm.workspace.ElmDetachProjectAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: intellij-elm]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

### Steps to reproduce

Open any project that will force the Elm plugin to load.

### IntelliJ IDE details (should contain the Elm plugin version and OS details)

```
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
GC: G1 Young Generation, G1 Old Generation
Registry:
  debugger.new.tool.window.layout=true
  search.everywhere.settings=true
  ide.experimental.ui=true
  scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins:
  intellij-elm (5.0.0-beta26)
Kotlin: 241.14494.240-IJ
Current Desktop: KDE
```

**Comment by ShrykeWindgrace** [comment]
Still have a 
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.elm.workspace.ElmDetachProjectAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: intellij-elm]

```
on a `WebStorm-24.1` + `5.0.0-beta28`
